name: Release Build
on: 
  push:
    tags: '*'

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Determine tag name
        run: echo tag_name=`basename ${{ github.ref }}` >> $GITHUB_ENV

      - name: Create tarball
        run: |
          mv build scigateway-${{ env.tag_name }}
          tar -czf scigateway-${{ env.tag_name }}.tar.gz scigateway-${{ env.tag_name }}

      - name: Create/update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./scigateway-${{ env.tag_name }}.tar.gz
          release: Release ${{ env.tag_name }}
          tag: ${{ env.tag_name }}
          prerelease: ${{ env.tag_name == 'prerelease' }}
          draft: false
