name: Release Build
on: 
  push:
    branches: master
    tags-ignore: prerelease

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Determine tag name
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]
          then
            echo tag_name=prerelease >> $GITHUB_ENV
          else
            echo tag_name=`basename ${{ github.ref }}` >> $GITHUB_ENV
          fi

      - name: Create tarball
        run: |
          mv build scigateway-${{ env.tag_name }}
          tar -czf scigateway-${{ env.tag_name }}.tar.gz scigateway-${{ env.tag_name }}

      - name: Create/update Release
        id: create_release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./scigateway-${{ env.tag_name }}.tar.gz
          release_name: Release ${{ env.tag_name }}
          tag: ${{ env.tag_name }}
          prerelease: ${{ env.tag_name == 'prerelease' }}
          draft: false
